import type {
  ProviderBackendConfig,
  ProviderDefinition,
  ProviderType,
  ProviderTypeInfo,
} from './types';
import { brand } from '../brand';

export const PROVIDER_DEFINITIONS: ProviderDefinition[] = [
  {
    id: 'bankofai',
    name: 'BANK OF AI',
    displayName: 'BANK OF AI',
    icon: '🧠',
    placeholder: 'sk-bankofai-...',
    model: 'BANK OF AI',
    requiresApiKey: true,
    docsUrl: brand.docsUrl,
    authMode: 'api_key',
    baseUrlMode: 'hidden',
    modelSelectionMode: 'hidden',
    supportsCustomBaseUrl: true,
    supportsCustomModelId: true,
    defaultBaseUrl: 'https://api.bankofai.io/v1',
    showBaseUrl: false,
    showModelId: false,
    modelIdPlaceholder: 'bankofai-chat',
    category: 'compatible',
    envVar: 'BANKOFAI_API_KEY',
    defaultModelId: 'MiniMax-M2.5',
    supportedAuthModes: ['api_key'],
    defaultAuthMode: 'api_key',
    supportsMultipleAccounts: true,
    sortOrder: 0,
    providerConfig: {
      baseUrl: 'https://api.bankofai.io/v1',
      api: 'openai-completions',
      apiKeyEnv: 'BANKOFAI_API_KEY',
    },
  },
  {
    id: 'anthropic',
    name: 'Anthropic',
    displayName: 'Anthropic',
    icon: '🤖',
    placeholder: 'sk-ant-api03-...',
    model: 'Claude',
    requiresApiKey: true,
    docsUrl: 'https://platform.claude.com/docs/en/api/overview',
    authMode: 'api_key',
    baseUrlMode: 'hidden',
    modelSelectionMode: 'hidden',
    supportsCustomBaseUrl: false,
    supportsCustomModelId: false,
    category: 'official',
    envVar: 'ANTHROPIC_API_KEY',
    defaultModelId: 'claude-opus-4-6',
    supportedAuthModes: ['api_key'],
    defaultAuthMode: 'api_key',
    supportsMultipleAccounts: true,
    sortOrder: 20,
  },
  {
    id: 'openai',
    name: 'OpenAI',
    displayName: 'OpenAI',
    icon: '💚',
    placeholder: 'sk-proj-...',
    model: 'GPT',
    requiresApiKey: true,
    docsUrl: 'https://platform.openai.com/docs',
    authMode: 'api_key',
    baseUrlMode: 'hidden',
    modelSelectionMode: 'hidden',
    supportsCustomBaseUrl: false,
    supportsCustomModelId: false,
    category: 'official',
    envVar: 'OPENAI_API_KEY',
    defaultModelId: 'gpt-5.2',
    isOAuth: true,
    supportsApiKey: true,
    supportedAuthModes: ['api_key', 'oauth_browser'],
    defaultAuthMode: 'api_key',
    supportsMultipleAccounts: true,
    sortOrder: 30,
    providerConfig: {
      baseUrl: 'https://api.openai.com/v1',
      api: 'openai-responses',
      apiKeyEnv: 'OPENAI_API_KEY',
    },
  },
  {
    id: 'google',
    name: 'Google',
    displayName: 'Google',
    icon: '🔷',
    placeholder: 'AIza...',
    model: 'Gemini',
    requiresApiKey: true,
    apiKeyUrl: 'https://aistudio.google.com/app/apikey',
    docsUrl: 'https://ai.google.dev/gemini-api/docs',
    authMode: 'api_key',
    baseUrlMode: 'hidden',
    modelSelectionMode: 'hidden',
    supportsCustomBaseUrl: false,
    supportsCustomModelId: false,
    category: 'official',
    envVar: 'GEMINI_API_KEY',
    defaultModelId: 'gemini-3.1-pro-preview',
    isOAuth: true,
    supportsApiKey: true,
    supportedAuthModes: ['api_key', 'oauth_browser'],
    defaultAuthMode: 'api_key',
    supportsMultipleAccounts: true,
    sortOrder: 40,
  },
  {
    id: 'openrouter',
    name: 'OpenRouter',
    displayName: 'OpenRouter',
    icon: '🌐',
    placeholder: 'sk-or-v1-...',
    model: 'Multi-Model',
    requiresApiKey: true,
    authMode: 'api_key',
    baseUrlMode: 'hidden',
    modelSelectionMode: 'required',
    supportsCustomBaseUrl: false,
    supportsCustomModelId: true,
    showModelId: true,
    modelIdPlaceholder: 'anthropic/claude-opus-4.6',
    defaultModelId: 'anthropic/claude-opus-4.6',
    docsUrl: 'https://openrouter.ai/models',
    category: 'compatible',
    envVar: 'OPENROUTER_API_KEY',
    supportedAuthModes: ['api_key'],
    defaultAuthMode: 'api_key',
    supportsMultipleAccounts: true,
    sortOrder: 50,
    providerConfig: {
      baseUrl: 'https://openrouter.ai/api/v1',
      api: 'openai-completions',
      apiKeyEnv: 'OPENROUTER_API_KEY',
      headers: {
        'HTTP-Referer': brand.openRouterReferrer,
        'X-Title': brand.openRouterTitle,
      },
    },
  },
  {
    id: 'ark',
    name: 'ByteDance Ark',
    displayName: 'ByteDance Ark',
    icon: 'A',
    placeholder: 'your-ark-api-key',
    model: 'Doubao',
    requiresApiKey: true,
    authMode: 'api_key',
    baseUrlMode: 'optional',
    modelSelectionMode: 'required',
    supportsCustomBaseUrl: true,
    supportsCustomModelId: true,
    defaultBaseUrl: 'https://ark.cn-beijing.volces.com/api/v3',
    showBaseUrl: true,
    showModelId: true,
    modelIdPlaceholder: 'ep-20260228000000-xxxxx',
    docsUrl: 'https://www.volcengine.com/',
    category: 'official',
    envVar: 'ARK_API_KEY',
    supportedAuthModes: ['api_key'],
    defaultAuthMode: 'api_key',
    supportsMultipleAccounts: true,
    sortOrder: 80,
    providerConfig: {
      baseUrl: 'https://ark.cn-beijing.volces.com/api/v3',
      api: 'openai-completions',
      apiKeyEnv: 'ARK_API_KEY',
    },
  },
  {
    id: 'moonshot',
    name: 'Moonshot (CN)',
    displayName: 'Moonshot (CN)',
    icon: '🌙',
    placeholder: 'sk-...',
    model: 'Kimi',
    requiresApiKey: true,
    authMode: 'api_key',
    baseUrlMode: 'hidden',
    modelSelectionMode: 'hidden',
    supportsCustomBaseUrl: false,
    supportsCustomModelId: false,
    defaultBaseUrl: 'https://api.moonshot.cn/v1',
    defaultModelId: 'kimi-k2.5',
    docsUrl: 'https://platform.moonshot.cn/',
    category: 'official',
    envVar: 'MOONSHOT_API_KEY',
    supportedAuthModes: ['api_key'],
    defaultAuthMode: 'api_key',
    supportsMultipleAccounts: true,
    sortOrder: 90,
    providerConfig: {
      baseUrl: 'https://api.moonshot.cn/v1',
      api: 'openai-completions',
      apiKeyEnv: 'MOONSHOT_API_KEY',
      models: [
        {
          id: 'kimi-k2.5',
          name: 'Kimi K2.5',
          reasoning: false,
          input: ['text'],
          cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 },
          contextWindow: 256000,
          maxTokens: 8192,
        },
      ],
    },
  },
  {
    id: 'siliconflow',
    name: 'SiliconFlow (CN)',
    displayName: 'SiliconFlow (CN)',
    icon: '🌊',
    placeholder: 'sk-...',
    model: 'Multi-Model',
    requiresApiKey: true,
    authMode: 'api_key',
    baseUrlMode: 'hidden',
    modelSelectionMode: 'required',
    supportsCustomBaseUrl: false,
    supportsCustomModelId: true,
    defaultBaseUrl: 'https://api.siliconflow.cn/v1',
    showModelId: true,
    modelIdPlaceholder: 'deepseek-ai/DeepSeek-V3',
    defaultModelId: 'deepseek-ai/DeepSeek-V3',
    docsUrl: 'https://docs.siliconflow.cn/cn/userguide/introduction',
    category: 'compatible',
    envVar: 'SILICONFLOW_API_KEY',
    supportedAuthModes: ['api_key'],
    defaultAuthMode: 'api_key',
    supportsMultipleAccounts: true,
    sortOrder: 100,
    providerConfig: {
      baseUrl: 'https://api.siliconflow.cn/v1',
      api: 'openai-completions',
      apiKeyEnv: 'SILICONFLOW_API_KEY',
    },
  },
  {
    id: 'minimax-portal',
    name: 'MiniMax (Global)',
    displayName: 'MiniMax (Global)',
    icon: '☁️',
    placeholder: 'sk-...',
    model: 'MiniMax',
    requiresApiKey: false,
    authMode: 'oauth_device',
    baseUrlMode: 'hidden',
    modelSelectionMode: 'hidden',
    supportsCustomBaseUrl: false,
    supportsCustomModelId: false,
    isOAuth: true,
    supportsApiKey: true,
    defaultModelId: 'MiniMax-M2.5',
    apiKeyUrl: 'https://intl.minimaxi.com/',
    docsUrl: 'https://intl.minimaxi.com/',
    category: 'official',
    envVar: 'MINIMAX_API_KEY',
    supportedAuthModes: ['oauth_device', 'api_key'],
    defaultAuthMode: 'oauth_device',
    supportsMultipleAccounts: true,
    sortOrder: 110,
    providerConfig: {
      baseUrl: 'https://api.minimax.io/anthropic',
      api: 'anthropic-messages',
      apiKeyEnv: 'MINIMAX_API_KEY',
    },
  },
  {
    id: 'minimax-portal-cn',
    name: 'MiniMax (CN)',
    displayName: 'MiniMax (CN)',
    icon: '☁️',
    placeholder: 'sk-...',
    model: 'MiniMax',
    requiresApiKey: false,
    authMode: 'oauth_device',
    baseUrlMode: 'hidden',
    modelSelectionMode: 'hidden',
    supportsCustomBaseUrl: false,
    supportsCustomModelId: false,
    isOAuth: true,
    supportsApiKey: true,
    defaultModelId: 'MiniMax-M2.5',
    apiKeyUrl: 'https://platform.minimaxi.com/',
    docsUrl: 'https://platform.minimaxi.com/',
    category: 'official',
    envVar: 'MINIMAX_CN_API_KEY',
    supportedAuthModes: ['oauth_device', 'api_key'],
    defaultAuthMode: 'oauth_device',
    supportsMultipleAccounts: true,
    sortOrder: 120,
    providerConfig: {
      baseUrl: 'https://api.minimaxi.com/anthropic',
      api: 'anthropic-messages',
      apiKeyEnv: 'MINIMAX_CN_API_KEY',
    },
  },
  {
    id: 'qwen-portal',
    name: 'Qwen',
    displayName: 'Qwen',
    icon: '☁️',
    placeholder: 'sk-...',
    model: 'Qwen',
    requiresApiKey: false,
    authMode: 'oauth_device',
    baseUrlMode: 'hidden',
    modelSelectionMode: 'hidden',
    supportsCustomBaseUrl: false,
    supportsCustomModelId: false,
    isOAuth: true,
    defaultModelId: 'coder-model',
    docsUrl: 'https://portal.qwen.ai/',
    category: 'official',
    envVar: 'QWEN_API_KEY',
    supportedAuthModes: ['oauth_device'],
    defaultAuthMode: 'oauth_device',
    supportsMultipleAccounts: true,
    sortOrder: 130,
    providerConfig: {
      baseUrl: 'https://portal.qwen.ai/v1',
      api: 'openai-completions',
      apiKeyEnv: 'QWEN_API_KEY',
    },
  },
  {
    id: 'ollama',
    name: 'Ollama',
    displayName: 'Ollama',
    icon: '🦙',
    placeholder: 'Not required',
    requiresApiKey: false,
    authMode: 'local',
    baseUrlMode: 'optional',
    modelSelectionMode: 'required',
    supportsCustomBaseUrl: true,
    supportsCustomModelId: true,
    defaultBaseUrl: 'http://localhost:11434/v1',
    showBaseUrl: true,
    showModelId: true,
    modelIdPlaceholder: 'qwen3:latest',
    docsUrl: 'https://ollama.com/',
    category: 'local',
    supportedAuthModes: ['local'],
    defaultAuthMode: 'local',
    supportsMultipleAccounts: true,
    sortOrder: 140,
  },
  {
    id: 'custom',
    name: 'Custom',
    displayName: 'Custom',
    icon: '⚙️',
    placeholder: 'API key...',
    requiresApiKey: true,
    authMode: 'api_key',
    baseUrlMode: 'required',
    modelSelectionMode: 'required',
    supportsCustomBaseUrl: true,
    supportsCustomModelId: true,
    showBaseUrl: true,
    showModelId: true,
    modelIdPlaceholder: 'your-provider/model-id',
    docsUrl: brand.docsUrl,
    docsUrlZh: brand.docsUrl,
    category: 'custom',
    envVar: 'CUSTOM_API_KEY',
    supportedAuthModes: ['api_key'],
    defaultAuthMode: 'api_key',
    supportsMultipleAccounts: true,
    sortOrder: 999,
  },
];

const PROVIDER_DEFINITION_MAP = new Map(
  PROVIDER_DEFINITIONS.map((definition) => [definition.id, definition]),
);

export function getProviderDefinition(
  type: ProviderType | string,
): ProviderDefinition | undefined {
  return PROVIDER_DEFINITION_MAP.get(type as ProviderType);
}

export function getProviderTypeInfo(
  type: ProviderType,
): ProviderTypeInfo | undefined {
  return getProviderDefinition(type);
}

export function getProviderEnvVar(type: string): string | undefined {
  return getProviderDefinition(type)?.envVar;
}

export function getProviderDefaultModel(type: string): string | undefined {
  return getProviderDefinition(type)?.defaultModelId;
}

export function getProviderBackendConfig(
  type: string,
): ProviderBackendConfig | undefined {
  return getProviderDefinition(type)?.providerConfig;
}

export function getProviderUiInfoList(): ProviderTypeInfo[] {
  return [...PROVIDER_DEFINITIONS].sort(
    (left, right) => (left.sortOrder ?? Number.MAX_SAFE_INTEGER) - (right.sortOrder ?? Number.MAX_SAFE_INTEGER),
  );
}

export function getKeyableProviderTypes(): string[] {
  return PROVIDER_DEFINITIONS.filter((definition) => definition.envVar).map(
    (definition) => definition.id,
  );
}
